`Function` type checking now checks the return last (fixes #610).
The interpreter stores the result type of a `Function` before the
argument types. By doing so, the return type is in a consistent place
regardless of the argument count. The type system has always checked the
result first, then arguments. All seemed well for a long time.

A recent commit (specifically, 2d6f19d4, from a month ago) changed the
signature of `Coroutine.build` (and `build_with`) to require that the
`Function` supply the same type the `Coroutine` returns. The signature
became the following:

```
build(fn: Function(Coroutine[A, B] => A)): Coroutine[A, B]
```

Suppose a user forgets to return a value as follows:

```
import (Coroutine) coroutine
define f(a: Coroutine[Integer, Unit]) {}
var v = Coroutine.build(f)
```

Here is the before and after on the error message generated:

```
SyntaxError: Argument #1 to Coroutine.build is invalid:
Expected Type: Function (Coroutine[Unit, ?])
Received Type: Function (Coroutine[Integer, Unit])
=====
SyntaxError: Argument #1 to Coroutine.build is invalid:
Expected Type: Function (Coroutine[Integer, Unit] => Integer)
Received Type: Function (Coroutine[Integer, Unit])
```